apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
  - name: web-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: mysql-pv
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: mysql-pv-claim