apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
      type: back-end
  template:
    metadata:
      labels:
        app: backend-app
        type: back-end
    spec:
      containers:
      - name: backend-container
        image: quay.io/bahgat_20/clinic:backend