apiVersion: v1
kind: Pod
metadata:
  name: backendpod
  namespace: bahgat-20-dev

spec:
  containers:
  - name: backend
    image: quay.io/bahgat_20/clinic:backend
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "400Mi"