apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  namespace: bahgat-20-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
    spec:
      containers:
      - name: db
        image: quay.io/bahgat_20/clinic:databaseimage
        resources:
          requests:
            cpu: 500m
            memory: 1G
          limits:
            cpu: 1G
            memory: 2G