apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: bahgat-20-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx